//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCC_Reference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/FormWebServer")]
    public partial class WebServiceResponse : object
    {
        
        private string errorCodek__BackingFieldField;
        
        private string errorMsgk__BackingFieldField;
        
        private string resultDatak__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<errorCode>k__BackingField", IsRequired=true)]
        public string errorCodek__BackingField
        {
            get
            {
                return this.errorCodek__BackingFieldField;
            }
            set
            {
                this.errorCodek__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<errorMsg>k__BackingField", IsRequired=true)]
        public string errorMsgk__BackingField
        {
            get
            {
                return this.errorMsgk__BackingFieldField;
            }
            set
            {
                this.errorMsgk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<resultData>k__BackingField", IsRequired=true)]
        public string resultDatak__BackingField
        {
            get
            {
                return this.resultDatak__BackingFieldField;
            }
            set
            {
                this.resultDatak__BackingFieldField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scc.com.cn", ConfigurationName="SCC_Reference2.IMacIntfWS")]
    public interface IMacIntfWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scc.com.cn/IMacIntfWS/macIntf", ReplyAction="http://scc.com.cn/IMacIntfWS/macIntfResponse")]
        SCC_Reference2.macIntfResponse macIntf(SCC_Reference2.macIntfRequest request);
        
        //[System.ServiceModel.OperationContractAttribute(Action= "http://scc.com.cn/IMacIntfWS/macIntf", ReplyAction="http://scc.com.cn/IMacIntfWS/macIntfResponse")]
        //System.Threading.Tasks.Task<SCC_Reference2.macIntfResponse> macIntfAsync(SCC_Reference2.macIntfRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="macIntf", WrapperNamespace="http://scc.com.cn", IsWrapped=true)]
    public partial class macIntfRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scc.com.cn", Order=0)]
        public string methodInvoke;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scc.com.cn", Order=1)]
        public string input;
        
        public macIntfRequest()
        {
        }
        
        public macIntfRequest(string methodInvoke, string input)
        {
            this.methodInvoke = methodInvoke;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="macIntfResponse", WrapperNamespace="http://scc.com.cn", IsWrapped=true)]
    public partial class macIntfResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://scc.com.cn", Order=0)]
        public SCC_Reference2.WebServiceResponse macIntfResult;
        
        public macIntfResponse()
        {
        }
        
        public macIntfResponse(SCC_Reference2.WebServiceResponse macIntfResult)
        {
            this.macIntfResult = macIntfResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IMacIntfWSChannel : SCC_Reference2.IMacIntfWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MacIntfWSClient : System.ServiceModel.ClientBase<SCC_Reference2.IMacIntfWS>, SCC_Reference2.IMacIntfWS
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MacIntfWSClient() : 
                base(MacIntfWSClient.GetDefaultBinding(), MacIntfWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMacIntfWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MacIntfWSClient(EndpointConfiguration endpointConfiguration) : 
                base(MacIntfWSClient.GetBindingForEndpoint(endpointConfiguration), MacIntfWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MacIntfWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MacIntfWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MacIntfWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MacIntfWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MacIntfWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SCC_Reference2.macIntfResponse macIntf(SCC_Reference2.macIntfRequest request)
        {
            return base.Channel.macIntf(request);
        }
        
        //public System.Threading.Tasks.Task<SCC_Reference2.macIntfResponse> macIntfAsync(SCC_Reference2.macIntfRequest request)
        //{
        //    return base.Channel.macIntfAsync(request);
        //}
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMacIntfWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMacIntfWS))
            {
                return new System.ServiceModel.EndpointAddress("http://test.scc.com.cn/wsservice/macWS");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MacIntfWSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMacIntfWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MacIntfWSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMacIntfWS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMacIntfWS,
        }
    }
}
